#!/usr/bin/env python3
"""Render a Gazebo Sim heightmap world + model from tile metadata YAML.

We do NOT implement a terrain engine — Gazebo Harmonic's built-in
<heightmap> geometry consumes the PNG directly. This script only
emits the small SDF strings that wire the PNG, size, and material
into the world.
"""
from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

import yaml


MODEL_CONFIG_TEMPLATE = """\
<?xml version="1.0"?>
<model>
  <name>lunar_dem_terrain</name>
  <version>1.0</version>
  <sdf version="1.10">model.sdf</sdf>
  <author>
    <name>lunar_south_pole_gazebo (generated)</name>
  </author>
  <description>
    LOLA-derived heightmap terrain. Generated by
    scripts/generate_gazebo_world.py from {meta_relpath}.
  </description>
</model>
"""

MODEL_SDF_TEMPLATE = """\
<?xml version="1.0"?>
<sdf version="1.10">
  <model name="lunar_dem_terrain">
    <static>true</static>
    <link name="link">
      <collision name="collision">
        <geometry>
          <heightmap>
            <uri>{png_uri}</uri>
            <size>{w} {h} {vscale}</size>
            <pos>0 0 0</pos>
            <sampling>1</sampling>
          </heightmap>
        </geometry>
      </collision>
      <visual name="visual">
        <geometry>
          <heightmap>
            <uri>{png_uri}</uri>
            <size>{w} {h} {vscale}</size>
            <pos>0 0 0</pos>
            <sampling>1</sampling>
            <texture>
              <size>{w}</size>
              <diffuse>{color_uri}</diffuse>
              <normal>{png_uri}</normal>
            </texture>
          </heightmap>
        </geometry>
        <material>
          <ambient>0.75 0.75 0.75 1</ambient>
          <diffuse>1.0 1.0 1.0 1</diffuse>
          <specular>0.1 0.1 0.1 1</specular>
        </material>
      </visual>
    </link>
  </model>
</sdf>
"""

WORLD_SDF_TEMPLATE = """\
<?xml version="1.0"?>
<sdf version="1.10">
  <world name="lunar_south_pole">
    <physics name="moon" type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>

    <gravity>0 0 -1.62</gravity>
    <atmosphere type="adiabatic"/>

    <!-- GUI camera + scene parameters are set via the gz-sim
         gui-config flag so the default toolbar, entity tree, and
         interactive view control all remain functional. See
         ros2_ws/src/.../gui/gui.config. -->

    <scene>
      <ambient>0.18 0.18 0.20 1</ambient>
      <background>0.01 0.01 0.03 1</background>
      <grid>false</grid>
      <shadows>true</shadows>
    </scene>

    <!-- Low-elevation solar light, characteristic of the lunar south pole. -->
    <light type="directional" name="sun">
      <pose>0 0 1500 0 0 0</pose>
      <direction>-0.6 -0.3 -0.4</direction>
      <diffuse>1 0.97 0.92 1</diffuse>
      <specular>0.5 0.5 0.5 1</specular>
      <cast_shadows>true</cast_shadows>
    </light>

    <include>
      <uri>model://lunar_dem_terrain</uri>
      <pose>0 0 {terrain_z_offset} 0 0 0</pose>
    </include>

    {rocks_include}
  </world>
</sdf>
"""

EMPTY_WORLD_TEMPLATE = """\
<?xml version="1.0"?>
<sdf version="1.10">
  <world name="lunar_south_pole_empty">
    <physics name="moon" type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <gravity>0 0 -1.62</gravity>
    <atmosphere type="adiabatic"/>
    <scene>
      <ambient>0.02 0.02 0.02 1</ambient>
      <background>0 0 0 1</background>
      <grid>false</grid>
    </scene>
    <light type="directional" name="sun">
      <pose>0 0 50 0 0 0</pose>
      <direction>-0.95 0.0 -0.30</direction>
      <diffuse>1 0.95 0.85 1</diffuse>
      <specular>0.5 0.5 0.5 1</specular>
      <cast_shadows>true</cast_shadows>
    </light>
    <!-- Flat plane as a stand-in until the DEM heightmap is generated. -->
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>2048 2048</size></plane></geometry>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>2048 2048</size></plane></geometry>
          <material><ambient>0.18 0.18 0.18 1</ambient></material>
        </visual>
      </link>
    </model>
  </world>
</sdf>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--meta", required=True, type=Path,
                    help="metadata YAML produced by normalize_heightmap.py")
    ap.add_argument("--pkg", required=True, type=Path,
                    help="path to the ROS 2 package "
                         "(ros2_ws/src/lunar_south_pole_gazebo)")
    ap.add_argument("--include-rocks", action="store_true",
                    help="emit <include uri=model://lunar_rocks/> in the world")
    ap.add_argument("--write-empty", action="store_true",
                    help="also (re)write the lunar_south_pole_empty.sdf fallback")
    args = ap.parse_args()

    if not args.meta.is_file():
        print(f"[gen-world] metadata YAML not found: {args.meta}",
              file=sys.stderr)
        return 2
    if not args.pkg.is_dir():
        print(f"[gen-world] package dir not found: {args.pkg}",
              file=sys.stderr)
        return 2

    meta = yaml.safe_load(args.meta.read_text())
    w = float(meta["tile_width_m"])
    h = float(meta["tile_height_m"])
    vscale = float(meta["vertical_scale_m"])
    png_path = Path(meta["heightmap_png"]).resolve()
    # The colorize step writes <heightmap>_color.png alongside the
    # heightmap. If it exists, use it as the heightmap diffuse texture.
    color_path = png_path.with_name(
        png_path.stem.replace("heightmap", "color") + png_path.suffix)
    png_uri = f"file://{png_path}"
    color_uri = (f"file://{color_path}" if color_path.is_file()
                 else png_uri)

    terrain_dir = args.pkg / "models" / "lunar_dem_terrain"
    terrain_dir.mkdir(parents=True, exist_ok=True)
    (terrain_dir / "model.config").write_text(
        MODEL_CONFIG_TEMPLATE.format(meta_relpath=str(args.meta)))
    (terrain_dir / "model.sdf").write_text(
        MODEL_SDF_TEMPLATE.format(png_uri=png_uri, color_uri=color_uri,
                                  w=w, h=h, vscale=vscale))
    print(f"[gen-world] wrote {terrain_dir / 'model.sdf'} "
          f"(size={w}×{h} m, vscale={vscale:.3f} m)")

    worlds_dir = args.pkg / "worlds"
    worlds_dir.mkdir(parents=True, exist_ok=True)

    rocks_include = (
        "<include><uri>model://lunar_rocks</uri></include>"
        if args.include_rocks else ""
    )
    # Anchor the terrain at z=0 so the viewer camera (at +z) actually
    # looks at it. Heightmap pixel value 0 → world z=0; pixel 65535 →
    # world z=vscale.
    terrain_z_offset = 0.0
    # Place the GUI camera high above one corner, looking back at the
    # tile centre.
    cam_x = -w * 0.6
    cam_y = -h * 0.6
    cam_z = vscale * 2.5 + 200.0
    cam_pitch = 0.45         # look slightly downward (rad)
    cam_yaw = 0.785          # 45° toward +X +Y

    (worlds_dir / "lunar_south_pole_dem.sdf").write_text(
        WORLD_SDF_TEMPLATE.format(
            rocks_include=rocks_include,
            terrain_z_offset=terrain_z_offset))
    # cam vars retained for future use
    _ = (cam_x, cam_y, cam_z, cam_pitch, cam_yaw)
    print(f"[gen-world] wrote {worlds_dir / 'lunar_south_pole_dem.sdf'}")

    if args.write_empty or not (worlds_dir / "lunar_south_pole_empty.sdf").exists():
        (worlds_dir / "lunar_south_pole_empty.sdf").write_text(EMPTY_WORLD_TEMPLATE)
        print(f"[gen-world] wrote {worlds_dir / 'lunar_south_pole_empty.sdf'}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
